name: "Test, Build, and Lint"

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Check for build cache
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install node dependencies
        if: steps.cache-modules.outputs.cache-hit != true
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{secrets['NPM_TOKEN']}}
          yarn install

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn run build

      - name: Run test
        run: yarn run test


